

# yaml files should not be empty which throws an error
# schema is nothing but how many columns our data is having and its data types and column names


COLUMNS : 
  ID                        :  int64  
  Customer_ID               :  int64  
  Month                     :  int64  
  Name                      :  object 
  Age                       :  float64
  SSN                       :  float64
  Occupation                :  object 
  Annual_Income             :  float64
  Monthly_Inhand_Salary     :  float64
  Num_Bank_Accounts         :  float64
  Num_Credit_Card           :  float64
  Interes_Rate              :  float64
  Num_of_Loan               :  float64
  Type_of_Loan              :  object 
  Delay_from_due_date       :  float64
  Num_of_Delayed_Payment    :  float64
  Changed_Credit_Limit      :  float64
  Num_Credit_Inquiries      :  float64
  Credit_Mix                :  object 
  Outstanding_Debt          :  float64
  Credit_Utilization_Ratio  :  float64
  Crdit_History_Age         :  float64
  Payment_of_min_amount     :  object 
  Total_EMI_per_month       :  float64
  Amount_invested_monthly   :  float64
  Payment_behaviour         :  object 
  Monthly_balance           :  float64
  Credit_score              :  object


TARGET_COLUMN :
  name :   Credit_score